-- T4.1a — Club: extend `club` with description/privacy/invite_code (phase-4-backlog.md §4.24
-- AC1-AC21, scoping session 2026-09-23/24; Create Club Premium-gating reversal 2026-09-25).
--
-- ============================================================================
-- WRITTEN 2026-09-25. NOT YET APPLIED to production, NOT YET VERIFIED live —
-- same two-step gate as every other migration in this repo: write inert ->
-- review -> apply + record real evidence as a separate step. Whoever applies
-- this MUST update this banner with genuine verification output (see
-- VERIFICATION below) before checking T4.1a off as done anywhere in tasks/*.
-- ============================================================================
--
-- Scope note: `club` (id, name, created_at) and `club_member` (user_id PK,
-- club_id, role, joined_at — one-club-per-user via the PK, per §4.19) already
-- exist (20260923200000_club_war_schema.sql, T4.2a) — this migration only
-- ADDS columns to `club`, no new tables. `owner_id` is deliberately NOT a
-- column here: `club_member.role = 'owner'` is already the single source of
-- truth for who owns a club (T4.2a) — a denormalized `club.owner_id` would be
-- a second copy of the same fact, same reasoning T4.2a itself used to leave
-- `user.club_id` alone.
--
-- `privacy`: 'public' (direct join, no request/approval) or 'invite_only'
-- (needs `invite_code`) — phase-4-backlog.md T4.1's AC1-AC21 scoping.
-- `invite_code` is `text`, not generated by a DB expression: the API
-- generates and retries on the unique constraint (simpler than a Postgres
-- collision-retry loop, and lets the API log a metric on retries if that
-- ever becomes useful). Random and regenerable, no expiry (closed
-- 2026-09-24, AC16-AC21).
--
-- Create Club's Premium gate itself is NOT a DB constraint here — same
-- reasoning as T4.2b's `isPremiumClub()`: a wrong or premature DB-level rule
-- is much harder to walk back than an API-layer check, and T4.20b (the real
-- Apple verification) isn't built yet, so a DB CHECK against `subscription`
-- would just be encoding today's "always false" stub permanently into the
-- schema. The gate lives in `backend/lib/club/premium.ts`, checked before
-- the insert.

begin;

alter table "club"
  add column "description" text,
  add column "privacy" text not null default 'public' check (privacy in ('public', 'invite_only')),
  add column "invite_code" text unique;

commit;

-- ============================================================================
-- ROLLBACK
-- ============================================================================
-- begin;
--
-- alter table "club"
--   drop column if exists "invite_code",
--   drop column if exists "privacy",
--   drop column if exists "description";
--
-- commit;
--
-- Pure column drop — `club` has zero rows until T4.1's Create Club ships (no
-- Club War can create one either, blocked on the same Premium gate), so no
-- data-loss risk at the time this migration is written.

-- ============================================================================
-- VERIFICATION (run after applying — required real evidence, same discipline
-- as every other migration here. NONE of this has been run yet; do not mark
-- T4.1a done anywhere until it has.)
-- ============================================================================
-- Expect 3 new columns on club:
--   select column_name, data_type, is_nullable, column_default
--    from information_schema.columns
--    where table_schema = 'public' and table_name = 'club'
--      and column_name in ('description', 'privacy', 'invite_code');
--
-- Expect an invalid privacy value to be genuinely refused (inside
-- begin/rollback, a real club id if one exists, or skip this specific check
-- if `club` is still empty — see the note above):
--   insert into "club" (name, privacy) values ('QA Test Club', 'bogus');
--   -- ERROR: new row for relation "club" violates check constraint "club_privacy_check"
--
-- Expect invite_code uniqueness to be genuinely enforced:
--   insert into "club" (name, invite_code) values ('QA Test A', 'DUPECODE');
--   insert into "club" (name, invite_code) values ('QA Test B', 'DUPECODE');
--   -- second insert => ERROR: duplicate key value violates unique constraint "club_invite_code_key"
